export const CHANGE_TOP_BANNERS = "recommend/CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMENDS = "recommend/CHANGE_HOT_RECOMMENDS";
export const CHANGE_NEW_ALBUMS = "recommend/CHANGE_NEW_ALBUMS";
export const CHANGE_HOT_RADIOS = "recommend/CHANGE_HOT_RADIOS";
export const CHANGE_SETTLE_SINGERS = "recommend/CHANGE_SETTLE_SINGERS";
export const CHANGE_UP_RANKING_LIST = "recommend/CHANGE_UP_RANKING_LIST";
export const CHANGE_NEW_RANKING_LIST = "recommend/CHANGE_NEW_RANKING_LIST";
export const CHANGE_ORG_RANKING_LIST = "recommend/CHANGE_ORG_RANKING_LIST";

export const CHANGE_USER_LOGIN = "recommend/CHANGE_USER_LOGIN";
